"use server"

// MFA (Multi-Factor Authentication) server actions.
//
// Built on the official Supabase Auth SDK (supabase.auth.mfa.*). The previous
// implementation hand-rolled HTTP calls to /auth/v1/mfa/* — those paths do not
// exist in GoTrue (correct: /auth/v1/factors, /factors/{id}/challenge,
// /factors/{id}/verify) and every call returned 404. Do not reintroduce them.
//
// MFA is enforced for general_manager and admin roles (they cannot unenroll).
// Other roles can optionally enable MFA.

import { createClient } from "@/lib/supabase/server"
import { createAdminClient } from "@/lib/supabase/admin"
import { getCurrentUser } from "@/lib/auth/authorization"
import { writeAuditLog } from "@/lib/auth/sessions"
import { moduleLogger } from "@/lib/logger"

const log = moduleLogger("mfa")

type MfaActionResult = {
  success: boolean
  error?: string
  /** SVG QR markup returned by our own Supabase Auth server — render locally */
  qrCode?: string
  /** Base32-encoded secret for manual entry (enrollment only) */
  secret?: string
  /** Factor ID (enrollment/verification) */
  factorId?: string
  /** Whether MFA is now enabled */
  enabled?: boolean
}

// Best-effort per-instance verify throttling. On serverless each instance has
// its own Map, so this is a backstop — TODO: replace with the shared
// Upstash-backed limiter from src/lib/rate-limit.ts.
const VERIFY_LIMIT = 5
const VERIFY_WINDOW_MS = 5 * 60 * 1000
const verifyAttempts = new Map<string, { count: number; resetAt: number }>()

function verifyRateOk(userId: string): boolean {
  const now = Date.now()
  const entry = verifyAttempts.get(userId)
  if (!entry || entry.resetAt <= now) {
    if (verifyAttempts.size > 10_000) verifyAttempts.clear()
    verifyAttempts.set(userId, { count: 1, resetAt: now + VERIFY_WINDOW_MS })
    return true
  }
  if (entry.count >= VERIFY_LIMIT) return false
  entry.count += 1
  return true
}

/**
 * Check if the current user's role requires MFA.
 * general_manager and admin roles MUST have MFA enabled.
 */
export async function isMfaRequired(): Promise<boolean> {
  const user = await getCurrentUser()
  if (!user) return false
  return user.role === "general_manager" || user.role === "admin"
}

/**
 * Enroll a new TOTP factor for the current user via the official SDK.
 *
 * Returns the QR SVG markup (generated by our own auth server) and the base32
 * secret for manual entry. The factor is unverified until verifyMfaCode()
 * succeeds with the first authenticator code.
 */
export async function enrollMfa(): Promise<MfaActionResult> {
  try {
    const user = await getCurrentUser()
    if (!user) return { success: false, error: "Not authenticated." }

    const supabase = await createClient()
    const { data, error } = await supabase.auth.mfa.enroll({
      factorType: "totp",
      friendlyName: `EliteDev-${user.id.slice(0, 8)}`,
      issuer: "EliteDev",
    })

    if (error) {
      log.error({ userId: user.id, error: error.message }, "MFA enrollment failed")
      return { success: false, error: error.message }
    }

    log.info({ userId: user.id, factorId: data.id }, "MFA factor enrolled")

    return {
      success: true,
      qrCode: data.totp.qr_code,
      secret: data.totp.secret,
      factorId: data.id,
    }
  } catch (e) {
    log.error({ error: e }, "MFA enrollment error")
    return { success: false, error: e instanceof Error ? e.message : "Unknown error." }
  }
}

/**
 * Verify a TOTP code against an enrolled factor (challenge → verify).
 * Rate-limited per user: 5 attempts per 5 minutes.
 */
export async function verifyMfaCode(
  factorId: string,
  code: string
): Promise<MfaActionResult> {
  try {
    const user = await getCurrentUser()
    if (!user) return { success: false, error: "Not authenticated." }

    if (!verifyRateOk(user.id)) {
      log.warn({ userId: user.id, factorId }, "MFA verify rate limit exceeded")
      return { success: false, error: "Too many attempts. Try again in 5 minutes." }
    }

    const supabase = await createClient()

    const { data: challenge, error: challengeError } = await supabase.auth.mfa.challenge({ factorId })
    if (challengeError) {
      return { success: false, error: challengeError.message }
    }

    const { error: verifyError } = await supabase.auth.mfa.verify({
      factorId,
      challengeId: challenge.id,
      code,
    })

    if (verifyError) {
      log.warn({ userId: user.id, factorId }, "MFA verification failed")
      return { success: false, error: "Invalid code." }
    }

    // Update the user's two_factor_enabled flag in our users table
    const admin = createAdminClient()
    await admin
      .from("users")
      .update({ two_factor_enabled: true, updated_at: new Date().toISOString() })
      .eq("id", user.id)

    // Audit log
    await writeAuditLog({
      tenantId: user.tenantId,
      actorId: user.authUserId,
      module: "security",
      action: "mfa_enabled",
      entityType: "user",
      entityId: user.id,
      newValues: { factorId },
    })

    log.info({ userId: user.id, factorId }, "MFA verified and enabled")

    return { success: true, enabled: true, factorId }
  } catch (e) {
    log.error({ error: e }, "MFA verification error")
    return { success: false, error: e instanceof Error ? e.message : "Unknown error." }
  }
}

/**
 * Unenroll (disable) a TOTP factor for the current user.
 * Rejected when MFA is required for the user's role.
 */
export async function unenrollMfa(factorId: string): Promise<MfaActionResult> {
  try {
    const user = await getCurrentUser()
    if (!user) return { success: false, error: "Not authenticated." }

    if (await isMfaRequired()) {
      return {
        success: false,
        error: "MFA is required for your role and cannot be disabled.",
      }
    }

    const supabase = await createClient()
    const { error } = await supabase.auth.mfa.unenroll({ factorId })

    if (error) {
      return { success: false, error: error.message }
    }

    // Update the user's two_factor_enabled flag
    const admin = createAdminClient()
    await admin
      .from("users")
      .update({ two_factor_enabled: false, two_factor_secret: null, updated_at: new Date().toISOString() })
      .eq("id", user.id)

    // Audit log
    await writeAuditLog({
      tenantId: user.tenantId,
      actorId: user.authUserId,
      module: "security",
      action: "mfa_disabled",
      entityType: "user",
      entityId: user.id,
      newValues: { factorId },
    })

    log.info({ userId: user.id, factorId }, "MFA factor unenrolled")

    return { success: true, enabled: false }
  } catch (e) {
    log.error({ error: e }, "MFA unenrollment error")
    return { success: false, error: e instanceof Error ? e.message : "Unknown error." }
  }
}

/**
 * List all enrolled MFA factors for the current user (official SDK).
 */
export async function listMfaFactors(): Promise<{
  success: boolean
  factors?: Array<{ id: string; type: string; friendly_name?: string; status: string }>
  error?: string
}> {
  try {
    const user = await getCurrentUser()
    if (!user) return { success: false, error: "Not authenticated." }

    const supabase = await createClient()
    const { data, error } = await supabase.auth.mfa.listFactors()

    if (error) {
      return { success: false, error: error.message }
    }

    return {
      success: true,
      factors: (data?.all ?? []).map((f) => ({
        id: f.id,
        type: f.factor_type,
        friendly_name: f.friendly_name,
        status: f.status,
      })),
    }
  } catch (e) {
    log.error({ error: e }, "MFA list factors error")
    return { success: false, error: e instanceof Error ? e.message : "Unknown error." }
  }
}
