import Link from 'next/link';
import { ArrowRight, Building2, CheckCircle2, ShieldCheck, BarChart3, Users, Truck, KeyRound } from 'lucide-react';

const capabilities = [
  { icon: Truck, title: 'Fleet command center', text: 'Drivers, vehicles, assignments, maintenance and operations in one dashboard.' },
  { icon: BarChart3, title: 'Business intelligence', text: 'Live operating metrics, accounting, invoices, expenses, and reports.' },
  { icon: Users, title: 'Company workspaces', text: 'Team roles and tenant-isolated data for every company workspace.' },
  { icon: ShieldCheck, title: 'Enterprise security', text: 'Supabase authentication and Row Level Security keep company data separated.' },
];

export default function PlatformPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white selection:bg-blue-500/30">
      <header className="border-b border-white/10 bg-slate-950/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6"><Link href="/" className="flex items-center gap-2 font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-purple-600"><Building2 className="h-5 w-5" /></span>Elite Platform</Link><div className="flex items-center gap-3"><Link href="/" className="text-sm text-white/65 hover:text-white">Home</Link><Link href="/platform/login" className="text-sm text-white/75 hover:text-white">Log in</Link><Link href="/platform/register" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold hover:bg-blue-500">Start free</Link></div></div></header>
      <section className="relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(59,130,246,.22),transparent_38%),radial-gradient(circle_at_80%_25%,rgba(139,92,246,.15),transparent_25%)]" /><div className="relative mx-auto max-w-5xl px-6 py-24 text-center md:py-32"><div className="mx-auto inline-flex items-center gap-2 rounded-full border border-blue-400/25 bg-blue-400/10 px-4 py-2 text-sm text-blue-200"><Building2 className="h-4 w-4" /> Built for transport and fleet companies</div><h1 className="mx-auto mt-6 max-w-4xl text-5xl font-bold tracking-tight md:text-6xl">Your company, your workspace, <span className="bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">one powerful platform.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/65">Discover Elite Fleet’s unified B2B operating system. Each company gets a secure, white-label-ready workspace while using the same modern dashboard experience.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/platform/register" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3 font-semibold hover:bg-blue-500">Create company workspace <ArrowRight className="h-4 w-4" /></Link><Link href="/platform/login" className="inline-flex items-center justify-center rounded-xl border border-white/15 bg-white/5 px-6 py-3 font-semibold hover:bg-white/10">Sign in to dashboard</Link></div></div></section>
      <section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{capabilities.map(item => <div key={item.title} className="rounded-2xl border border-white/10 bg-slate-900/60 p-6 transition hover:border-blue-400/30"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-500/10"><item.icon className="h-5 w-5 text-blue-400" /></div><h2 className="mt-5 font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-white/55">{item.text}</p></div>)}</div></section>
      <section className="border-y border-white/10 bg-slate-900/40"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-widest text-purple-400">The company journey</p><h2 className="mt-3 text-3xl font-bold">Explore first. Register when ready.</h2><p className="mt-4 leading-7 text-white/60">There is no separate dashboard deployment per company. Every organization signs in to the unified <code className="rounded bg-white/10 px-1.5 py-0.5 text-blue-200">/dashboard</code>, with data and branding scoped to its own tenant.</p><Link href="/platform/register" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold hover:bg-blue-500">Start your workspace <ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-2xl border border-white/10 bg-slate-950/70 p-6"><div className="flex items-center gap-3 text-blue-300"><KeyRound className="h-5 w-5" /><span className="font-medium">What is included</span></div><ul className="mt-5 space-y-4 text-sm text-white/75">{['Secure company registration and login','Tenant-isolated drivers, vehicles, invoices and expenses','White-label name, logo and brand colors','Analytics, accounting, reports and team management'].map(item => <li key={item} className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-green-400" />{item}</li>)}</ul></div></div></section>
      <section className="mx-auto max-w-4xl px-6 py-24 text-center"><h2 className="text-3xl font-bold">Ready to build your fleet workspace?</h2><p className="mt-3 text-white/60">Create your company account and go directly to the unified tenant-aware dashboard.</p><Link href="/platform/register" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3 font-semibold hover:bg-blue-500">Start Free Trial <ArrowRight className="h-4 w-4" /></Link></section>
    </main>
  );
}
